#!/bin/bash
#
# (Try to) Show the dependency list for applying a given commit on the current
# branch.
#

maxdeps=$2

function handle_one {
	((maxdeps--))
	if [ $maxdeps -eq 0 ]; then
		exit
	fi

	stable commit-in-tree $1
	if [ $? -eq 1 ]; then
		return
	fi

	echo $1
	for i in $(stable-deps.py $1); do
		handle_one $i
	done
}

handle_one $1
