#!/bin/bash
#
# Show commits which exist in a given range, but don't exist in the current
# branch.
#

. show-missing-iter

if [ "$#" -ne 1 ]; then
        echo "Usage: stable show-missing <commit range>"
        exit 1
fi

function simple_print {
	echo $(git log -1 --oneline $1)
}

show_missing_iter $1 simple_print
